public class VariablesTheme {
    public static void main(String[] args) {
        System.out.println("1.Вывод характеристик компьютера");
        char s = 'S';
        System.out.print("Процессор: " + s);
        char o = 'o';
        System.out.print("" + o);
        char c = 'C';
        System.out.println("" + c);
        String videocard = "DirectX 9";
        System.out.println("Видеоадаптер: " + videocard);
        int processor = 3000;
        char g = 'Г';
        char tse = 'ц';
        System.out.print("Частота процессора: " + processor);
        System.out.print(" " + g);
        System.out.println("" + tse);
        byte bit = 8;
        System.out.print("Один байт= " + bit);
        String bitName = "бит";
        System.out.println(" " + bitName);
        float memory = 7.70f;
        System.out.println("Установленная память: " + memory);
        short systemType = 64;
        System.out.print("Тип системы:" + systemType);
        String systemType2 = "-разрядная";
        System.out.println("" + systemType2);
        long drive = 512L;
        System.out.println("Жёсткий диск " + drive);
        boolean screen = true;
        System.out.println("Есть ли монитор у компьютера? " + screen);
        double screen2 = 23.8;
        System.out.println("Характеристики монитора: " + screen2);
        System.out.println();
        System.out.println("2. Расчет стоимости товара со скидкой");
        int cost1 = 100;
        int cost2 = 200;
        int total1 = cost2 + cost1;
        System.out.println("Общая стоимость товаров без скидки= " + total1);
        int cost3 = total1 * 11 / 100;
        System.out.println("Сумма скидки= " + cost3);
        int total2 = total1 - cost3;
        System.out.println("Общая сумма товаров со скидкой= " + total2);
        System.out.println();
        System.out.println("3.Вывод слова JAVA");
        System.out.println("   J    a  v     v  a       ");
        System.out.println("   J   a a  v   v  a a     ");
        System.out.println("J  J  aaaaa  V V  aaaaa     ");
        System.out.println(" JJ  a     a  V  a     a");
        System.out.println();
        System.out.println("4.Вывод min и max значений целых числовых типов");
        byte b1 = -128;
        byte b2 = 127;
        System.out.println("байт минимум: " + b1);
        System.out.println("байт максимум: " + b2);
        b1++;
        b2--;
        System.out.println("байт инкремент: " + b1);
        System.out.println("байт декремент: " + b2);
        System.out.println();
        short sh1 = -32768;
        short sh2 = 32767;
        System.out.println("шорт минимум: " + sh1);
        System.out.println("шорт максимум: " + sh2);
        sh1++;
        sh2--;
        System.out.println("шорт инкремент: " + sh1);
        System.out.println("шорт декремент: " + sh2);
        System.out.println();
        int i1 = -2147483648;
        int i2 = 2147483647;
        System.out.println("инт минимум: " + i1);
        System.out.println("инт максимум: " + i2);
        i1++;
        i2--;
        System.out.println("инт инкремент: " + i1);
        System.out.println("инт декремент: " + i2);
        System.out.println();
        long l1 = -9223372036854775808L;
        long l2 = 9223372036854775807L;
        System.out.println("лонг максимум: " + l1);
        System.out.println("лонг минимум: " + l2);
        l1++;
        l2--;
        System.out.println("лонг инкремент: " + l1);
        System.out.println("лонг декремент: " + l2);
        System.out.println();
        System.out.println("5.Перестановка значений переменных");
        int digit1 = 2;
        int digit2 = 5;
        System.out.println("исходные цифры " + digit1 + " и " + digit2);
        System.out.println();
        int digit3 = digit1;
        digit1 = digit2;
        digit2 = digit3;
        System.out.println("с помощью третьей переменной");
        System.out.println("цифры " + digit1 + " и " + digit2);
        System.out.println();
        System.out.println("с помощью арифметических операций");
        int sum = digit1 + digit2;
        digit1 = sum - digit1;
        digit2 = sum - digit2;
        System.out.println("цифры " + digit1 + " и " + digit2);
        System.out.println(digit2);
        int digit4 = digit1 ^ digit2;
        System.out.println("Представление числа: " + digit1 + " в двоичной системе исчисления: " +
                 Integer.toBinaryString(digit1));
        System.out.println("Представление числа: " + digit2 + " в двоичной системе исчисления: " +
                 Integer.toBinaryString(digit2));
        System.out.println("Представление числа: " + digit4 + " в двоичной системе исчисления: " +
                 Integer.toBinaryString(digit3));
        System.out.println();
        System.out.println("6.Вывод символов и их кодов");
        char dollar = '$';
        char asterisk = '*';
        char atSign = '@';
        char verticalBar = '|';
        char tilde = '~';
        System.out.println(dollar + " = 00100100");
        System.out.println(asterisk + " = 00101010");
        System.out.println(atSign + " = 01000000");
        System.out.println(verticalBar + " = 01111100");
        System.out.println(tilde + " = 01111110");
        System.out.println();
        System.out.println("7. Вывод в консоль ASCII-арт Дюка");
        char slash = '/';
        char slash2 = '\\';
        char underlining = '_';
        char semicircle = '(';
        char semicircle2 = ')';
        System.out.println("    " + slash + slash2);
        System.out.println("   " + slash + "  " + slash2);
        System.out.println("  " + slash + underlining + semicircle + " " + semicircle2 + slash2);
        System.out.println(" " + slash + "      " + slash2);
        System.out.println("" + slash + underlining +
                 underlining + underlining +
                 underlining + slash + slash2 + underlining + underlining + slash2);
        System.out.println();
        System.out.println("8. Вывод количества сотен, десятков и единиц числа");
        int number = 123;
        System.out.println("Число " + number + " содержит:");
        int hundreds = number / 100;
        System.out.println("сотен - " + hundreds);
        int dozens = (number - hundreds * 100) / 10;
        System.out.println("десятков - " + dozens);
        int units = (number - hundreds * 100) - (dozens * 10);
        System.out.println("единиц - " + units);
        System.out.println();
        System.out.println("9. Вывод времени");
        int time = 86399;
        int hours = time / 3600;
        int time2 = time - hours * 3600;
        int minutes = time2 / 60;
        int seconds = time2 - minutes * 60;
        System.out.println(hours + ":" + minutes + ":" + seconds);
    }
}